# Generated by Django 2.2.3 on 2019-09-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Ad')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Adınızı giriniz.', max_length=100, verbose_name='Ad')),
                ('surname', models.CharField(blank=True, help_text='Soyadınızı giriniz.', max_length=100, verbose_name='Soyad')),
                ('robot_name', models.CharField(blank=True, help_text='Robot adını giriniz.', max_length=100, verbose_name='Robot adı')),
                ('email', models.EmailField(help_text='E-postanızı giriniz.', max_length=50, null=True, verbose_name='E-posta :')),
                ('phone', models.CharField(help_text='Telefonunuzu giriniz.', max_length=100, null=True, verbose_name='Telefon :')),
                ('school_name', models.CharField(blank=True, help_text='Okulunuzun adını giriniz.', max_length=100, verbose_name='Okul Adı')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robonish.Robot', verbose_name='Kategori seçiniz.')),
            ],
            options={
                'verbose_name_plural': 'Kayıt',
                'ordering': ['id'],
            },
        ),
    ]
